### ISSUE TITLE
Usage with SublimeLinter?

### ISSUE THREAD

**Issue by joeldbirch** [standard/standardx#8]
Hello, thanks for this package.

I have SublimeLinter setup with SublimeLinter-contrib-standard and I'm wondering if I can get it to use the standardx overrides. I was hoping merely installing standardx would do the trick, but SublimeLinter still highlights, for example, trailing commas even though I have add to this to my package.json:

```json

"eslintConfig": {
    "rules": {
      "comma-dangle": 0
    }
  },

```

Does anyone have any ideas on how to get this working? Thanks in advance.

**Comment by joeldbirch** [comment]
I seem to have succeeded in altering SublimeLinter-contrib-standard to make it do what I want. [If it helps, here is my forked repo](https://github.com/joeldbirch/SublimeLinter-contrib-standard). Please feel free to close this issue, if you like.

**Comment by Flet** [comment]
Nice! You should publish your fork to package control! :)

Yeah since the cmd to execute `standard` is hard coded in `sublimeLinter-contrib-standard` there is not a way to easily switch it.

Another hacky way to fix it would be to alias `standard` to execute `standardx` on the machine.

The most elegant way would probably be to update `sublimeLinter-contrib-standard` to add another setting to pick the command thats executed. I would happily accept a PR on it, but I don't have the capacity to do it myself.
